services:
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
        - proxy
        - containerd
    environment:
        - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    secrets:
      - CONTAINDERD_TUNNEL_TOKEN

networks:
    proxy:
      external: true
    containerd:

secrets:
  CONTAINDERD_TUNNEL_TOKEN:
    external: true