services:
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
        - proxy
        - containerd
    environment:
        - TUNNEL_TOKEN=/run/secrets/CONTAINERD_TUNNEL_TOKEN
    secrets:
      - CONTAINERD_TUNNEL_TOKEN

networks:
    proxy:
      external: true
    containerd:

secrets:
  CONTAINERD_TUNNEL_TOKEN:
    external: true