services:
  core:
    container_name: searxng-core
    deploy:
      labels:
        traefik.enable: ${TRAEFIK_ENABLE}
        traefik.swarm.network: ${TRAEFIK_SWARM_NETWORK}
        traefik.http.routers.searxng.rule: ${TRAEFIK_HTTP_ROUTERS_SEARXNG_RULE}
        traefik.http.services.searxng.loadbalancer.server.port: ${TRAEFIK_HTTP_SERVICES_SEARXNG_LOADBALANCER_SERVER_PORT}
        traefik.http.routers.searxng.entrypoints: ${TRAEFIK_HTTP_ROUTERS_SEARXNG_ENTRYPOINTS}
        traefik.http.routers.searxng.tls: ${TRAEFIK_HTTP_ROUTERS_SEARXNG_TLS}
        traefik.http.routers.searxng.tls.certresolver: ${TRAEFIK_HTTP_ROUTERS_SEARXNG_TLS_CERTRESOLVER}
        traefik.http.routers.searxng.service: ${TRAEFIK_HTTP_ROUTERS_SEARXNG_SERVICE}
      placement:
        constraints:
          - node.role == manager    
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    restart: always
#    ports:
#      - ${SEARXNG_HOST:+${SEARXNG_HOST}:}${SEARXNG_PORT:-8080}:${SEARXNG_PORT:-8080}
#    env_file: ./.env
    volumes:
      - core-config:${CORE_CONFIG_VOLUME}:Z
      - core-data:${CORE_DATA_VOLUME}
    networks:
      - proxy
      - searxing

  valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: always
    volumes:
      - valkey-data:${VALKEY_DATA_VOLUME}
    networks:
      - proxy
      - searxing

volumes:
  core-data:  
  core-config:  
  valkey-data:

networks:
  proxy:
    external: true
  searxing: